### ISSUE TITLE
Add metric for partitions' log size

### ISSUE THREAD

**Issue by weeco** [cloudworkz/kafka-minion#10]
**Use case**

I don't know of any prometheus exporter which exports Kafka's partition log size. This is a great metric to identify the space usage for each partition.  Additionally the historic graph can show you the impact of compact events in terms of space usage.

**The problem**

While the Kafka protocol supports a command in their admin client API to describe the log directories (https://kafka.apache.org/21/javadoc/org/apache/kafka/clients/admin/DescribeLogDirsResult.html), this is not yet implemented in Sarama. An issue has been created for this: https://github.com/Shopify/sarama/issues/1313

There's yet to check whether other Kafka Go libraries already support this command.

PR submitted: https://github.com/Shopify/sarama/pull/1520

**Comment by erkiesken** [comment]
We get this metric via the jmx exporter on brokers. I.e. add jmx exporter jar from [here](https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar) and use it in brokers as:

```KAFKA_OPTS="-javaagent:/opt/kafka/libs/jmx_prometheus_javaagent-0.12.0.jar=9102:/etc/kafka/jmx-exporter-config.yaml"```

And in the exporter config (see [other example configs](https://github.com/prometheus/jmx_exporter/tree/master/example_configs)):

```
      - pattern: kafka.log<type=Log, name=(.+), topic=(.+), partition=(.+)><>Value
        name: kafka_log_$1
        labels:
          topic: "$2"
          partition: "$3"
```
