### ISSUE TITLE
Add custom attributes

### ISSUE THREAD

**Issue by mikekamornikov** [cloudworkz/kafka-minion#37]
Currently I can't distinguish metrics between different Kafka clusters monitored by several Kafka-minion instances. The idea is to add a "cluster_name" variable to my dashboard and filter by it. But what I get from `kafka-minion` doesn't contain any cluster specific attribute.

I think the best option here is to add a config option with static custom attributes. Something like:
```
METRICS_CUSTOM_ATTRIBUTE="cluster_name=my dev cluster,aaa=123"
```
This way we can tag different kafka-minion instances.

**Comment by godwhoa** [comment]
If you are using gcp or ec2 service discovery for Prometheus jobs you can add instance metadata as labels to your metrics in that job:
```
  - job_name: "kafka_minion"
    gce_sd_configs:
      - project: "{{ gcp_project }}"
        filter: "(labels.prometheus_exporter = \"minion\")"
        port: 9000
    relabel_configs:
      - source_labels: [__meta_gce_label_cluster]
        target_label: cluster
```
